include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "/example/**" # Exclude example directory from analysis

linter:
  rules:
    # full list: https://dart-lang.github.io/linter/lints/index.html.
    avoid_print: true
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_redundant_argument_values: true
    unnecessary_final: true
    unnecessary_breaks: true
    sort_child_properties_last: true
    avoid_slow_async_io: true
    avoid_positional_boolean_parameters: true
    avoid_void_async: true
    combinators_ordering: true
    directives_ordering: true
    implicit_call_tearoffs: true
    noop_primitive_operations: true
    parameter_assignments: true
    prefer_if_elements_to_conditional_expressions: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_parenthesis: true
    unnecessary_to_list_in_spreads: true
    use_colored_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_super_parameters: true
    always_put_control_body_on_new_line: true
    always_put_required_named_parameters_first: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    strict_top_level_inference: false
